schema: ["Autorisatie/Koppelvlak/bemiddelingsregister/bemiddelingsregister.graphql", "Autorisatie/Koppelvlak/indicateregister/indicatieregister.graphql"]
documents: "src/**/*.graphql"
extensions:
  endpoints:
    default:
      url: "http://localhost:4000/graphql"
