name: MD to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'RFC_test/**.md'
      # - 'docs/images/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Markdown to PDF and HTML
        uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: RFC_test
          output_dir: RFC_pdf
          images_dir: plantUMLsrc
          # for example <img src="./images/file-name.png">
          image_import: ../plantUMLsrc
          # Default is true, can set to false to only get PDF files
          build_html: false
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # name: upload
          path: RFC_pdf/

